export const summary = 'yg-config.yaml fields: version, reviewer model, quality thresholds, parallelism, reviewer timeout';

export const content = `# Configuration (yg-config.yaml)

\`yg-config.yaml\` lives in \`.yggdrasil/\` and controls the reviewer and
runtime behavior. It is generated by \`yg init\` and updated by \`yg init --upgrade\`.

## File structure

\`\`\`yaml
version: "4.4.0"

reviewer:
  model: claude-opus-4-5        # LLM model used for approve
  timeout_seconds: 120          # Timeout per reviewer call
  parallelism: 3                # Max concurrent approve calls

quality:
  min_coverage_pct: 80          # Minimum % of repo files with graph coverage
  max_unmapped_files: 50        # Hard cap on unmapped file count

\`\`\`

## Fields

### version

Matches the Yggdrasil CLI version that generated this config. The CLI
refuses to load a config with a version it doesn't recognize. Run
\`yg init --upgrade\` to migrate to a newer version.

### reviewer.model

The LLM model used for \`yg approve\`. Use the most capable model available
for your team's budget — reviewer accuracy directly affects rejection quality.

Changing the model does not cause existing approvals to expire. New approvals
use the new model.

### reviewer.timeout_seconds

Per-call timeout. If the LLM takes longer, approve fails with a timeout
error. Increase for large nodes with many source files.

Default: 120 seconds.

### reviewer.parallelism

Maximum concurrent LLM calls during a batch approve (\`--aspect\` or \`--flow\`).
Higher parallelism reduces wall-clock time but increases concurrent LLM spend.

Default: 3.

### quality.min_coverage_pct

Minimum percentage of repo files that must be covered by at least one
node's mapping. \`yg check\` emits a warning (not error) when below this
threshold.

This is a soft quality gate — CI does not block on coverage warnings,
only on hard errors (drift, validation failures, \`unmapped-files\` when
configured as strict).

### quality.max_unmapped_files

Hard cap on the number of unmapped files. When exceeded, \`yg check\`
emits an error that blocks CI.

## Upgrading

\`\`\`bash
node <path-to-yg> init --upgrade
\`\`\`

Reads the existing \`yg-config.yaml\`, applies migrations, and writes the
updated version. Run from the repository root. Review the diff before
committing — migrations may change defaults.

## Secrets

\`yg-config.yaml\` must not contain API keys or tokens. The CLI reads the
LLM API key from the environment (\`ANTHROPIC_API_KEY\` or equivalent).
Commit \`yg-config.yaml\` to the repository — it contains no secrets.
`;
