export const summary = 'yg-config.yaml fields: version, reviewer tiers, quality thresholds, parallelism';

export const content = `# Configuration (yg-config.yaml)

\`yg-config.yaml\` lives in \`.yggdrasil/\` and controls the reviewer and
runtime behavior. It is generated by \`yg init\` and updated by \`yg init --upgrade\`.

## yg-config.yaml reference

Full annotated example:

\`\`\`yaml
version: "5.0.0"

reviewer:
  tiers:
    standard:                       # Tier name — referenced by aspect reviewer.tier
      provider: ollama              # LLM provider (ollama, anthropic, openai, claude-code, ...)
      consensus: 1                  # Votes per aspect (1 = single call; odd >= 3 = majority vote)
      config:
        model: qwen3                # Model identifier for this provider
        temperature: 0              # Sampling temperature (0 = deterministic)
        endpoint: http://localhost:11434   # Required for ollama and openai-compatible
        max_tokens: auto            # Response budget: 'auto' or positive integer

quality:
  max_direct_relations: 10          # Max out-edges per node before wide-node warning
  max_mapping_source_files: 10      # Max source files per node before wide-node warning
\`\`\`

## Provider configs

v5 introduces named tiers. Each tier is an independent LLM configuration.
Aspects declare which tier they use via \`reviewer.tier: <name>\`. If no
\`tier:\` is set, the aspect uses the first tier defined in the config.

### reviewer.tiers.<name>

Tier name can be any string except the reserved word \`default\`. Convention:
use \`standard\` for the primary tier. Add a second tier (e.g. \`fast\`) for
aspects that can tolerate a cheaper model.

### reviewer.tiers.<name>.provider

One of: \`ollama\`, \`anthropic\`, \`openai\`, \`google\`, \`openai-compatible\`,
\`claude-code\`, \`codex\`, \`gemini-cli\`.

CLI providers (\`claude-code\`, \`codex\`, \`gemini-cli\`) do not require an API key —
they delegate to the installed CLI tool.

### reviewer.tiers.<name>.consensus

Number of independent reviewer calls per aspect. Must be a positive odd integer.

- \`1\` — single call, cheapest
- \`3\` — majority vote (2 of 3 must agree), more reliable

### reviewer.tiers.<name>.config

Provider-specific options passed to the LLM client:

| Field | Type | Notes |
|---|---|---|
| \`model\` | string | Required. Provider-specific model identifier. |
| \`temperature\` | number | Defaults to 0. Higher = more varied responses. |
| \`endpoint\` | string | Required for \`ollama\` and \`openai-compatible\`. |
| \`max_tokens\` | number\\|'auto' | Response budget. 'auto' queries the provider. |
| \`context_length_field\` | string | Ollama: field name in model info for context length. |
| \`timeout\` | number | Per-call timeout in seconds. |

## Multi-tier example

\`\`\`yaml
reviewer:
  tiers:
    fast:
      provider: ollama
      consensus: 1
      config:
        model: qwen3
        endpoint: http://localhost:11434
    thorough:
      provider: anthropic
      consensus: 3
      config:
        model: claude-opus-4-7
        temperature: 0
\`\`\`

Aspect using the thorough tier:

\`\`\`yaml
reviewer:
  type: llm
  tier: thorough
\`\`\`

Aspect using the default (first) tier — no \`tier:\` needed:

\`\`\`yaml
reviewer:
  type: llm
\`\`\`

## Secrets (yg-secrets.yaml)

API keys go in \`yg-secrets.yaml\`, NOT in \`yg-config.yaml\`.
\`yg-secrets.yaml\` is gitignored by default.

\`\`\`yaml
# .yggdrasil/yg-secrets.yaml  — gitignored, never commit
reviewer:
  anthropic:
    api_key: sk-ant-...
\`\`\`

\`yg-config.yaml\` itself must never contain credentials. Commit it to the
repository — it is safe to share.

## Quality thresholds

\`\`\`yaml
quality:
  max_direct_relations: 10          # Wide-node warning threshold
  max_mapping_source_files: 10      # Wide-node warning threshold
\`\`\`

Both fire warnings (not errors) when exceeded. Violations appear in \`yg check\`
output as \`wide-node\` warnings. Split large nodes into children to stay under
the thresholds.

## Upgrading

\`\`\`bash
node <path-to-yg> init --upgrade
\`\`\`

Reads the existing \`yg-config.yaml\`, applies migrations (including v4 → v5
reviewer format), and writes the updated version. Run from the repository root
only. Review the diff before committing.
`;
