"""Pure aggregation transforms for the analytics pipeline.

These functions reduce cleaned rows into summary metrics. Like the cleaning
transforms, they are deterministic: the same input rows always yield the same
aggregates, so a report generated today can be regenerated byte-for-byte from
the same source data tomorrow.
"""

from __future__ import annotations

from typing import Any, Iterable


def group_sum(rows: Iterable[dict[str, Any]], group_key: str, value_key: str) -> dict[Any, float]:
    """Sum ``value_key`` per distinct ``group_key``."""
    totals: dict[Any, float] = {}
    for row in rows:
        group = row.get(group_key)
        value = row.get(value_key)
        if value is None:
            continue
        totals[group] = totals.get(group, 0.0) + float(value)
    return totals


def group_count(rows: Iterable[dict[str, Any]], group_key: str) -> dict[Any, int]:
    """Count rows per distinct ``group_key``."""
    counts: dict[Any, int] = {}
    for row in rows:
        group = row.get(group_key)
        counts[group] = counts.get(group, 0) + 1
    return counts


def group_average(rows: Iterable[dict[str, Any]], group_key: str, value_key: str) -> dict[Any, float]:
    """Average ``value_key`` per distinct ``group_key``, ignoring missing values."""
    sums: dict[Any, float] = {}
    counts: dict[Any, int] = {}
    for row in rows:
        group = row.get(group_key)
        value = row.get(value_key)
        if value is None:
            continue
        sums[group] = sums.get(group, 0.0) + float(value)
        counts[group] = counts.get(group, 0) + 1
    return {group: sums[group] / counts[group] for group in sums}


def top_n(totals: dict[Any, float], n: int) -> list[tuple[Any, float]]:
    """Return the ``n`` highest-valued (key, value) pairs.

    Ties break on the key so the ordering is total and reproducible rather than
    dependent on dict insertion accidents.
    """
    ordered = sorted(totals.items(), key=lambda item: (-item[1], str(item[0])))
    return ordered[:n]
